name: backpacks
version: '${project.version}'
main: com.bigweas.backpacks.Backpacks
api-version: '1.20'
load: STARTUP
authors: [BigWeas]
description: a simple backpack plugin
website: bigweas.com
commands:
  backpack:
    description: access your backpack to store or collect items
    usage: /<command>
    permission: backpack.backpack
    aliases:
      - bp
      - pack
      - sack
permissions:
  backpack.backpack:
    description: allows players to use a backpack
    default: true

