name: backpacks
version: '${project.version}'
main: com.bigweas.backpacks.Backpacks
api-version: '1.20'
load: STARTUP
authors: [BigWeas]
description: a simple backpack plugin
website: bigweas.com
commands:
  god:
    description: toggle god mode (invincible)
    permission: backpack.god
    usage: /<command>
    aliases:
      - godmode
      - pro
  feed:
    description: feeds player to full hunger bars
    usage: /<command>
    permission: backpack.feed
  backpack:
    description: access your backpack to store or collect items
    usage: /<command>
    permission: backpack.backpack
    aliases:
      - bp
      - pack
      - sack
permissions:
  backpack.god:
    description: allows player to toggle god mode
    default: op
  backpack.feed:
    description: allows player to fill hunger bars immediately
    default: true
  backpack.backpack:
    description: allows players to use a backpack
    default: true

