name: backpacks
version: '${project.version}'
main: com.bigweas.backpacks.Backpacks
api-version: '1.20'
load: STARTUP
authors: [BigWeas]
description: a simple backpack plugin
website: bigweas.com
depend: [Vault]
commands:
  backpack:
    description: access your backpack to store or collect items
    usage: /<command>
    permission: backpacks.backpack
    aliases:
      - bp
      - pack
      - sack
  seebackpack:
    description: access the backpack of a target player
    usage: /<command> <playername>
    permission: backpacks.seebackpack
    aliases:
      - sb
      - backpacksee
  setdefaultbackpacksize:
    description: edits the config to change the default backpack size
    usage: /<command> <size>
    permission: backpacks.setdefaultbackpacksize
    aliases:
      - sdbs
  setbackpacksize:
    description: set the size of your backpack or a target player
    usage: /<command> <player> (optional) <size>
    permission: backpacks.setbackpacksize
    aliases:
      - sbs
  resetbackpack:
    description: reset the backpack to default size and clear inventory
    usage: /<command>
    permission: backpacks.resetbackpack
    aliases:
      - rbp
  balance:
    description: See your current balance
    usage: /<command>
    permission: backpacks.balance
    aliases:
      - bal
permissions:
  backpacks.backpack:
    description: allows players to use a backpack
    default: true
  backpacks.seebackpack:
    description: allows a player to see the backpack of others
    default: op
  backpacks.setdefaultbackpacksize:
    description: allows a player to set the default size of backpacks
    default: op
  backpacks.setbackpacksize:
    description: allows player to adjust the backpack size of their own or others' backpacks
    default: op
  backpacks.resetbackpack:
    description: allows player to reset the backpack to its default size and clear its inventory
    default: op
  backpacks.balance:
    description: allows a player to see their current balance
    default: true

